sudo: required
services: 
    - docker


before_install:
    - docker build -t djfwong/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true djfwong/docker-react npm run test -- --coverage
    
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react-tutorial"
    env: "DockerReactTutorial-env"
    bucket_name: "arn:aws:s3:::elasticbeanstalk-us-east-2-098097480152"
    bucket_path: "docker-react-tutorial"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

language: generic
    